// <auto-generated />
using System;
using Gdzie.Kupic.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gdzie.Kupic.Storage.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260614185439_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Auth.BuyerProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("BuyerProfiles");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Auth.ExternalLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuyerProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BuyerProfileId");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique();

                    b.ToTable("ExternalLogins");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Auth.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Catalogue.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Catalogue.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Chat.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttachmentKey")
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.HasIndex("ThreadId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Chat.ChatThread", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId");

                    b.HasIndex("PostId", "MerchantId")
                        .IsUnique();

                    b.ToTable("ChatThreads");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Infrastructure.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Location.SavedLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuyerProfileId")
                        .HasColumnType("uuid");

                    b.Property<Point>("Coordinates")
                        .IsRequired()
                        .HasColumnType("geography(Point,4326)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BuyerProfileId");

                    b.HasIndex("Coordinates");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Coordinates"), "GIST");

                    b.ToTable("SavedLocations");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Marketplace.Merchant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Merchants");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Marketplace.MerchantAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("MerchantAccounts");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Marketplace.MerchantBranch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressDisplayName")
                        .HasColumnType("text");

                    b.Property<Point>("Coordinates")
                        .IsRequired()
                        .HasColumnType("geography(Point,4326)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Coordinates");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Coordinates"), "GIST");

                    b.HasIndex("MerchantId");

                    b.ToTable("MerchantBranches");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Marketplace.MerchantResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId");

                    b.HasIndex("PostId", "MerchantId")
                        .IsUnique();

                    b.ToTable("MerchantResponses");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Marketplace.MerchantSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TagId");

                    b.HasIndex("MerchantId", "CategoryId", "TagId")
                        .IsUnique();

                    b.ToTable("MerchantSubscriptions");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Marketplace.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuyerProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Point>("Coordinates")
                        .IsRequired()
                        .HasColumnType("geography(Point,4326)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsLongLived")
                        .HasColumnType("boolean");

                    b.Property<string>("NotificationDispatchStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RadiusKm")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BuyerProfileId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Coordinates");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Coordinates"), "GIST");

                    b.HasIndex("TagId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Notifications.PostNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId");

                    b.HasIndex("PostId", "MerchantId")
                        .IsUnique();

                    b.ToTable("PostNotifications");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Notifications.PushSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PushSubscriptions");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Auth.BuyerProfile", b =>
                {
                    b.HasOne("Gdzie.Kupic.Storage.Entities.Auth.User", "User")
                        .WithOne("BuyerProfile")
                        .HasForeignKey("Gdzie.Kupic.Storage.Entities.Auth.BuyerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Auth.ExternalLogin", b =>
                {
                    b.HasOne("Gdzie.Kupic.Storage.Entities.Auth.BuyerProfile", "BuyerProfile")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("BuyerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuyerProfile");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Auth.PasswordResetToken", b =>
                {
                    b.HasOne("Gdzie.Kupic.Storage.Entities.Auth.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Auth.RefreshToken", b =>
                {
                    b.HasOne("Gdzie.Kupic.Storage.Entities.Auth.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Auth.User", b =>
                {
                    b.OwnsOne("Gdzie.Kupic.Storage.Entities.Common.BadDetails", "BanDetails", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("BannedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("BannedAt");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("BanDetails");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Catalogue.Tag", b =>
                {
                    b.HasOne("Gdzie.Kupic.Storage.Entities.Catalogue.Category", "Category")
                        .WithMany("Tags")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Chat.ChatMessage", b =>
                {
                    b.HasOne("Gdzie.Kupic.Storage.Entities.Auth.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gdzie.Kupic.Storage.Entities.Chat.ChatThread", "Thread")
                        .WithMany("Messages")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sender");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Chat.ChatThread", b =>
                {
                    b.HasOne("Gdzie.Kupic.Storage.Entities.Marketplace.Merchant", "Merchant")
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gdzie.Kupic.Storage.Entities.Marketplace.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Location.SavedLocation", b =>
                {
                    b.HasOne("Gdzie.Kupic.Storage.Entities.Auth.BuyerProfile", "BuyerProfile")
                        .WithMany("SavedLocations")
                        .HasForeignKey("BuyerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuyerProfile");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Marketplace.Merchant", b =>
                {
                    b.OwnsOne("Gdzie.Kupic.Storage.Entities.Common.BadDetails", "BanDetails", b1 =>
                        {
                            b1.Property<Guid>("MerchantId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("BannedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("BannedAt");

                            b1.HasKey("MerchantId");

                            b1.ToTable("Merchants");

                            b1.WithOwner()
                                .HasForeignKey("MerchantId");
                        });

                    b.Navigation("BanDetails");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Marketplace.MerchantAccount", b =>
                {
                    b.HasOne("Gdzie.Kupic.Storage.Entities.Marketplace.Merchant", "Merchant")
                        .WithMany("MerchantAccounts")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gdzie.Kupic.Storage.Entities.Auth.User", "User")
                        .WithOne("MerchantAccount")
                        .HasForeignKey("Gdzie.Kupic.Storage.Entities.Marketplace.MerchantAccount", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Marketplace.MerchantBranch", b =>
                {
                    b.HasOne("Gdzie.Kupic.Storage.Entities.Marketplace.Merchant", "Merchant")
                        .WithMany("MerchantBranches")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Gdzie.Kupic.Storage.Entities.Common.ContactDetails", "ContactDetails", b1 =>
                        {
                            b1.Property<Guid>("MerchantBranchId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Phone")
                                .HasColumnType("text")
                                .HasColumnName("Phone");

                            b1.Property<string>("Website")
                                .HasColumnType("text")
                                .HasColumnName("Website");

                            b1.HasKey("MerchantBranchId");

                            b1.ToTable("MerchantBranches");

                            b1.WithOwner()
                                .HasForeignKey("MerchantBranchId");
                        });

                    b.Navigation("ContactDetails");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Marketplace.MerchantResponse", b =>
                {
                    b.HasOne("Gdzie.Kupic.Storage.Entities.Marketplace.Merchant", "Merchant")
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gdzie.Kupic.Storage.Entities.Marketplace.Post", "Post")
                        .WithMany("MerchantResponses")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Marketplace.MerchantSubscription", b =>
                {
                    b.HasOne("Gdzie.Kupic.Storage.Entities.Catalogue.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gdzie.Kupic.Storage.Entities.Marketplace.Merchant", "Merchant")
                        .WithMany("Subscriptions")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gdzie.Kupic.Storage.Entities.Catalogue.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("Merchant");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Marketplace.Post", b =>
                {
                    b.HasOne("Gdzie.Kupic.Storage.Entities.Auth.BuyerProfile", "BuyerProfile")
                        .WithMany("Posts")
                        .HasForeignKey("BuyerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gdzie.Kupic.Storage.Entities.Catalogue.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gdzie.Kupic.Storage.Entities.Catalogue.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Gdzie.Kupic.Storage.Entities.Marketplace.UrgencyDetails", "Urgency", b1 =>
                        {
                            b1.Property<Guid>("PostId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("Deadline")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("UrgentDeadline");

                            b1.HasKey("PostId");

                            b1.ToTable("Posts");

                            b1.WithOwner()
                                .HasForeignKey("PostId");
                        });

                    b.Navigation("BuyerProfile");

                    b.Navigation("Category");

                    b.Navigation("Tag");

                    b.Navigation("Urgency");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Notifications.PostNotification", b =>
                {
                    b.HasOne("Gdzie.Kupic.Storage.Entities.Marketplace.Merchant", "Merchant")
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gdzie.Kupic.Storage.Entities.Marketplace.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Notifications.PushSubscription", b =>
                {
                    b.HasOne("Gdzie.Kupic.Storage.Entities.Auth.User", "User")
                        .WithMany("PushSubscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Gdzie.Kupic.Storage.Entities.Notifications.WebPushKeys", "Keys", b1 =>
                        {
                            b1.Property<Guid>("PushSubscriptionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AuthKey")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("AuthKey");

                            b1.Property<string>("P256dhKey")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("P256dhKey");

                            b1.HasKey("PushSubscriptionId");

                            b1.ToTable("PushSubscriptions");

                            b1.WithOwner()
                                .HasForeignKey("PushSubscriptionId");
                        });

                    b.Navigation("Keys")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Auth.BuyerProfile", b =>
                {
                    b.Navigation("ExternalLogins");

                    b.Navigation("Posts");

                    b.Navigation("SavedLocations");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Auth.User", b =>
                {
                    b.Navigation("BuyerProfile");

                    b.Navigation("MerchantAccount");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("PushSubscriptions");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Catalogue.Category", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Chat.ChatThread", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Marketplace.Merchant", b =>
                {
                    b.Navigation("MerchantAccounts");

                    b.Navigation("MerchantBranches");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Gdzie.Kupic.Storage.Entities.Marketplace.Post", b =>
                {
                    b.Navigation("MerchantResponses");
                });
#pragma warning restore 612, 618
        }
    }
}
