<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>13</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Gdzie.Kupic.Tests.Unit" />
    <InternalsVisibleTo Include="Gdzie.Kupic.Tests.Integration" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gdzie.Kupic.API.Contract\Gdzie.Kupic.API.Contract.csproj" />
    <ProjectReference Include="..\Gdzie.Kupic.Chat\Gdzie.Kupic.Chat.csproj" />
    <ProjectReference Include="..\Gdzie.Kupic.Marketplace\Gdzie.Kupic.Marketplace.csproj" />
    <ProjectReference Include="..\Gdzie.Kupic.Notifications\Gdzie.Kupic.Notifications.csproj" />
  </ItemGroup>

</Project>